#!/bin/bash

set +x

#. .env/bin/activate
#cd /app/torch-rnn/
#python scripts/preprocess.py \
#	--input_txt /data/in.txt \
#	--output_h5 /tmp/in.h5 \
#	--output_json /tmp/in.json
#
#rm -rf cv
#mkdir -p /data/cv
#ln -s /data/cv cv
#. /app/torch/install/bin/torch-activate
#th train.lua \
#	-input_h5 /tmp/in.h5 \
#	-input_json /tmp/in.json \
#	-gpu -1
#
#	-model_type rnn \
#	-num_layers 3 \
#	-rnn_size 256 \

cd /app/torch-rnn/
. /app/torch/install/bin/torch-activate
th sample.lua \
	-checkpoint /data/file.t7 \
	-gpu -1 \
	-sample_text "hej" \
	-length 100 \
	-temperature 0.8
